version: "3.8"
services:
    web:
      container_name: calculator-prod-container
      build:
        context: .
        dockerfile: Dockerfile.prod
      ports:
        - "8080:80"
      env_file:
        - ./.env

