FROM node:18-alpine3.15 AS build
ENV REACT_APP_NAME="My Calculator"
WORKDIR /app
COPY package.json .
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html