version: "3.8"
services:
    web:
      container_name: calculator-container
      # stdin_open: true
      # tty: true
      build: .
      volumes:
        - ./src:/app/src:ro
      ports:
        - "3000:3000"
      env_file:
        - ./.env

